services:
  drivvo-web:
    container_name: drivvo-web
    build:
      context: .
    environment:
      NODE_ENV: production
      PORT: 3000
    expose:
      - '3000'
    networks:
      - drivvo-stats-network
    restart: unless-stopped

networks:
  drivvo-stats-network:
    external: true
